# Generated by Django 4.2 on 2025-04-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(choices=[('CAR', 'Cardiologista'), ('ORT', 'Ortopedista'), ('NEU', 'Neurologita'), ('END', 'Endocrinologista'), ('PSI', 'Psiquiatria')], max_length=3)),
                ('crm', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGEN', 'agendado'), ('REAL', 'realizado'), ('CANC', 'cancelado')], max_length=4)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
